package dialog;

import fenetre.EnregistrerBox;
import javax.swing.JButton;
import javax.swing.JTextField;
import listener.ModeleListener;
import panel.EntrerMulti;

public class EnregistrerDialog extends javax.swing.JPanel {

    EnregistrerBox eb;

    public EnregistrerBox getEb() {
        return eb;
    }

    public EnregistrerDialog(EnregistrerBox eb) {
        this.eb = eb;
        initComponents();
        enregistrermodele.addActionListener(new ModeleListener(this, (EntrerMulti) ((eb.getFenetre()).getContentPane())));
    }

    public JButton getEnregistrermodele() {
        return enregistrermodele;
    }

    public JTextField getNommodele() {
        return nommodele;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enregistrermodele = new javax.swing.JButton();
        nommodele = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(368, 152));
        setMinimumSize(new java.awt.Dimension(368, 152));
        setPreferredSize(new java.awt.Dimension(368, 152));

        enregistrermodele.setBackground(new java.awt.Color(204, 204, 204));
        enregistrermodele.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enregistrermodele.setText("Enregistrer");

        nommodele.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nom du modele :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(enregistrermodele, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nommodele)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nommodele, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(enregistrermodele, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enregistrermodele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nommodele;
    // End of variables declaration//GEN-END:variables
}
